spring.application.name=CodeAssist

# H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# Spring Cloud
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

#Ollama config
spring.ai.ollama.base-url=${OLLAMA_URL}

#Qdrant config
qdrant.url=http://localhost:6333

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true